@startuml
class Robot 
{
   ICommandReceiver* cmdrcv
   IEngine* engines[2]
   double wheelRadius
   
   Run()
   Move(int direction, int distance)
   Rotate(int direction, angle)
}

abstract class ICommandReceiver
{
   virtual getCommand()
}

class TCPCommandReceiver
{
   int server_address
   int clientSocketFD

   Connect()
   getCommand()
}

class ConsoleCommandReceiver
{
   getCommand()
}

class ConsoleEngine 
{
   Run(int, int)
}

class GPIOEngine
{
   Run(int, int)
}

abstract class IEngine
{
   virtual Run(int signal, int value)
}

IEngine <|-- GPIOEngine
IEngine <|-- ConsoleEngine
ICommandReceiver <|-- TCPCommandReceiver
ICommandReceiver <|-- ConsoleCommandReceiver
Robot o-- IEngine : has 2 engines >
Robot o-- ICommandReceiver : has 1 >

@enduml
